GET http://localhost:3000/api/auth/test
Authorization :  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmOWQxY2QwZi0xYmI3LTRhMjYtOTBkNy0yNDM2MTg4OWU1ZmYiLCJpYXQiOjE2ODkyMDE3MjgsImV4cCI6MTY4OTIwMjYyOH0.bvJW9hZcC3vcRIX9N2XAmb1ZK28ZxhxXDmO2CEzs_Jo eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmOWQxY2QwZi0xYmI3LTRhMjYtOTBkNy0yNDM2MTg4OWU1ZmYiLCJpYXQiOjE2ODkyMDE3MDV9.y5gQlrVcCbVoYZfSuK4Gwf9B-4eMnQTvAgVaUPBZGPY  